### ISSUE TITLE
Installer dies on Windows 2008 Server

### ISSUE THREAD

**Issue by ArtS** [yysun/Git-Source-Control-Provider#1]
I downloaded VS2008 installer from http://gitscc.codeplex.com/ but when I run it it justs exits after running the preparatory procedures, leaving two messages in the event log:
1. Source: MsiInstaller
   Windows Installer reconfigured the product. Product Name: Git Source Control Provider. Product Version: 0.5.6. Product Language: 1033. Manufacturer: Yiyi Sun. Reconfiguration success or error status: 0.
2. Source: RestartManager
   Ending session 0 started ‎2010‎-‎07‎-‎27T02:14:57.436300100Z.

Can I somehow get around it?

Thanks

**Comment by yysun** [comment]
It should have been installed. If you open VS2008, go to Tools | Options.
And select Source Control | Plug-in Selection, do you see "Git Source Control Provder" in the drop-down?

**Comment by ArtS** [comment]
Excellent, that works.

It's worth including those instructions into some readme.txt file which gets opened at the end of installation, otherwise users are left clueless to the state of the system.
