### ISSUE TITLE
Performance Issue on Big Solutions

### ISSUE THREAD

**Issue by johnhaley81** [yysun/Git-Source-Control-Provider#13]
I was poking around trying to find any progress on this issue: http://gitscc.codeplex.com/workitem/16794
on GitHub but I couldn't find any. It sounded like a viable solution was found but the pull request wasn't implemented yet?

Any word on the status of this issue?

**Comment by yysun** [comment]
working on it as highest priority ... should see some results very soon.

**Comment by johnhaley81** [comment]
That's great! I love your extension but my application is too large to use it right now :(

**Comment by yysun** [comment]
I pushed a new build V0.8.8. Does it work better for you?

**Comment by johnhaley81** [comment]
The performance is much improved. Great job Yiyi!
