### ISSUE TITLE
When viewing the diff of a file, it shows all lines as being new.

### ISSUE THREAD

**Issue by johnhaley81** [yysun/Git-Source-Control-Provider#14]
Hey yysun,

When I'm looking at a diff of a file inside GSCP it shows all of the lines as deleted and then as re-added. When I do a diff inside TortoiseGit however it shows the added/modified/deleted lines correctly. The auto-formatting of the file hasn't changed (e.g. the tabs haven't been replaced by spaces or anything like that).

I couldn't find this issue on here so I just thought I'd let you know. Let me know if you need more information.

-John

**Comment by johnhaley81** [comment]
I just noticed that you can change the diff tool in the options menu. I switched it over to the TortioseMerge.exe tool and that's working nicely. Nevermind :)

**Comment by yysun** [comment]
Hi John,

There is a new beta build at http://gitscc.codeplex.com/workitem/16616 

yysun

**Comment by johnhaley81** [comment]
That seemed to fix the issue. Thanks for the quick response Yiyi :)

**Comment by yysun** [comment]
Thanks!
