### ISSUE TITLE
Icons are not in sync with status

### ISSUE THREAD

**Issue by mbohy** [yysun/Git-Source-Control-Provider#15]
I know of two ways in which your extension tells me about the status of my files: one is via an icon next to the file, and one is a tooltip shown when hovering over the file.

The tooltip always seems to be correct, but the icons sometimes are not.  For example the tooltip might say "Tracked" but the icon is the "New file" icon.  This only seems to happen when the file as it's named in the OS has different casing than its representation in Visual Studio.

For example, a file on disk may be named FOO.CPP and in the project it might be Foo.cpp.  In that case, the icon does not stay in sync with the file status.

**Comment by jsadeli** [comment]
This seems to be a refresh issue/bug. Forcing a refresh `(Right Click on file in Solution Explorer) > Git (master) > Refresh` fixes the icons for me, until it gets out of sync again.

**Comment by mbohy** [comment]
Refreshing doesn't do anything for me.  Again, the status is displayed correctly in the tooltip, but the icons are not correct.  Thanks though!

**Comment by sharwell** [comment]
This should be resolved in the next release. If you experience the problem again please reopen this issue.
