### ISSUE TITLE
Support TortoiseGit

### ISSUE THREAD

**Issue by AndreyNikiforov** [yysun/Git-Source-Control-Provider#2]
Add support for TortoiseGit along with GitExtensions

**Comment by yysun** [comment]
TortoiseGit is a Windows Explorer shell extension. You can right click solution/project within visual studio solution explorer, select "Open Folder in Windows Explorer". Then you can right click the within the Windows Explorer to access TortoiseGit.

**Comment by AndreyNikiforov** [comment]
Well, I was talking of the feature similar to "Launch GitExtensions", so right clicking in SolutionExplorer and then selecting Commit launches TortoiseGit Commit dialog, not GitExtensions.

**Comment by yysun** [comment]
I wasn't able to find out a way to launch TortoiseGit Commit dialog outside the windows explorer before. I just found it now. It is "C:\Program Files\TortoiseGit\bin\TortoiseProc.exe" /command:commit

I will add it in next release.

**Comment by AndreyNikiforov** [comment]
I checked v.0.6.0 and it does have a way to start tgit, but it is not what I envisioned. GitSCC should eliminate the need to switch to Windows Explorer/tgit. Something like:

in right click menu:
- Commit command that will call tgit commit window
- Sync command that will call tgit sync window

in Git submenu on right click menu:
- Diff to call tgit diff
- Show Log to call tgit Show Log
- Revert to call tgit Revert
- Branch to call tgit Branch
- Merge to call tgit Merge
- Resolve to call tgit Resolve
- Switch to call tgit Switch

**Comment by yysun** [comment]
OK, I will try it out.

**Comment by armando-fandango** [comment]
What is the status of this extension.. has this been worked out already ?

**Comment by yysun** [comment]
In V 0.6.2, which will be released in a few days, the git menu will be expanded. See screenshot here: http://gitscc.codeplex.com/wikipage?title=Project%20Roadmap&referringTitle=Home

**Comment by Buthrakaur** [comment]
The only thing I'm missing here is Blame command - could it be added?
