### ISSUE TITLE
Preserve staging checkboxes when refreshing

### ISSUE THREAD

**Issue by SLaks** [yysun/Git-Source-Control-Provider#22]
Whenever the pending changes window refreshes, all of the staging checkboxes are reset.

Can you remember which files were checked and re-check them after refreshing?

I use auto-refresh, so if I carefully select files to stage, then save any file, my selection is blown away.  This is rather annoying

(Which issue tracker do you use?)

**Comment by thoemmi** [comment]
I think this is fixed in V0.9.2

**Comment by SLaks** [comment]
Correct.

**Comment by thoemmi** [comment]
@SLaks could you close this issue then?

**Comment by SLaks** [comment]
Done
