### ISSUE TITLE
Iconsistent Line Endings Dialog viewing changed files

### ISSUE THREAD

**Issue by danspam** [yysun/Git-Source-Control-Provider#23]
When viewing changed files in the Git Pending Changes tab, the 'Inconsistent Line Endings' dialog appears, asking if you wish to normalize line endings. It looks like it occurs when generating the diff in the preview window. This dialog can appear continuously if you happen to be working on the file that is selected in the tab. I would rather not untick the 'always show this dialog' option as I find this dialog useful for other things.

**Comment by sharwell** [comment]
The text view used for displaying the diff has been changed to a library (AvalonEdit). This change likely corrected this problem, and I have not been able to reproduce this issue in the latest development builds.

If this problem appears for you again after the next release, please reopen this issue.
