### ISSUE TITLE
Visual Studio (Not Responding) Large Repo

### ISSUE THREAD

**Issue by dipeshc** [yysun/Git-Source-Control-Provider#28]
Visual Studio stops responding upon modification when using large repo (2.5GB and 9000+ commits)

**Comment by pasa-** [comment]
I also encountered serious slowdown (including slow build) or not-responding with large repo (QT). That cured turning off the git provider. On a 8-core machine, 

As a side note, I recall the poll time for refreshing is like 200ms, that is IMO is way too frequent, and problematic even for medium sized projects. It should be at leas configurable.

**Comment by vadimskipin** [comment]
Working on a project of average size (500mb repository) I also encountered some noticeable delays. After turning on SCC provider they are gone. My guess they caused by FS pooling (kernel time, disk IO affected).

**Comment by vadimskipin** [comment]
I mean turning OFF
