### ISSUE TITLE
Provider dose not work on a large project

### ISSUE THREAD

**Issue by lanwin** [yysun/Git-Source-Control-Provider#3]
I am not sure what is the problem. The Provider is installed and configured, but it still not show anything in my project tree.

I am here to test something if need.

**Comment by yysun** [comment]
Thanks lanwin.

Which version of Visual Studio do you have? VS 2008 or VS 2010, Express or Professional or Ultimate?

Is the issue you have similar to this: http://gitscc.codeplex.com/workitem/14070?

Regards,

yysun

**Comment by lanwin** [comment]
I use VS2010 Ultimate Eng + ReSharper. No i have no icon. VS looks like without Version Control.

**Comment by yysun** [comment]
What is your solution folder structure look like?

yysun

**Comment by lanwin** [comment]
.git and sln living in root folder. Subprojects live in a Source\ProjectName folder.

**Comment by yysun** [comment]
There was a bug similar to this that is fixed in V 0.5.7 (for VS2010).
http://gitscc.codeplex.com/workitem/14070

There was another bug if the subprojects are web site projects. It is targeted to be fixed in V 0.5.8. If you want I can email you the latest dev build for a test.

yysun

**Comment by lanwin** [comment]
Send you a message
