### ISSUE TITLE
Compare doesn't work in VS11 Beta

### ISSUE THREAD

**Issue by Buthrakaur** [yysun/Git-Source-Control-Provider#31]
I'm used to use "Compare..." command from "Changed files" sub-window quite a lot, but it looks like it's broken in VS11. It looks like it's not able to find the files to comare...

**Comment by jacargentina** [comment]
Does it work on VS 2012 ?

**Comment by sharwell** [comment]
The problem occurs when the built-in Visual Studio 2012 diff is disabled and no other diff tool has been configured. The status bar message resulting from this misconfiguration has been changed to the following.

```
Diff tool 'diffmerge.exe' is not available.
```
