### ISSUE TITLE
Use Visual Studio 2012's built-in comparer

### ISSUE THREAD

**Issue by SLaks** [yysun/Git-Source-Control-Provider#32]
VS2012 has a built-in differ, which allows the current file to be edited with full IntelliSense (as long as it was opened from the project)

Can GitSCP use this in VS2012?

(Either from right-click, Compare, and perhaps also embedded in the right pane)

**Comment by yysun** [comment]
To use vs 2012's built differ, the command is devenv /diff . 

Currently GitSCP supports setting the path the diff tool, but it does not support command line options. It is being work on.

**Comment by SLaks** [comment]
I already tried that, by writing a batch script to add the command-line
option.

However, the resulting diff view has neither syntax highlighting nor
in-project auto-complete.
To support that, I believe you need to invoke the diff from the VS API
directly.

On Mon, Jun 11, 2012 at 1:18 PM, Yiyi Sun <
reply@reply.github.com

> wrote:
> 
> To use vs 2012's built differ, the command is devenv /diff .
> 
> Currently GitSCP supports setting the path the diff tool, but it does not
> support command line options. It is being work on.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> 
> https://github.com/yysun/Git-Source-Control-Provider/issues/32#issuecomment-6250410

## 

Schabse Laks
@Schabse http://twitter.com/Schabse |
StackOverflowhttp://stackoverflow.com/users/34397/slaks
 | Blog http://blog.slaks.net/

**Comment by yysun** [comment]
Thanks for the hint. I'll search VS API then.
