### ISSUE TITLE
"Pending Changes Filter" view does not show changed files in VS2012

### ISSUE THREAD

**Issue by philippdolder** [yysun/Git-Source-Control-Provider#37]
When filtering "pending changes" in solution explorer view. It says: "All items have been filtered from view." Though when in normal mode I can see the "+" and other edit states of files.

I would love to have this supported. Though I'm not sure if it is a problem in VS or something missing in GitSourceControlProvider

**Comment by jacargentina** [comment]
That option is related to TFS AFAIK

**Comment by philippdolder** [comment]
I would assume that a "Source Control Provider" should be able to be notified of these events. The same mechanism as used to display the icons should be able to show the filter view correctly. Probably this is something that is not as expected in VS2012?

How hard is it for me to debug into it? I never did something with a Visual Studio extension

**Comment by sharwell** [comment]
I cannot reproduce this problem in the latest development build. When I click "Pending Changes Filter", the files which remain showing in Solution Explorer exactly match the set of files in the Pending Changes window.

If this problem appears for you again after the next release, please reopen this issue.
