### ISSUE TITLE
The icons for the various states of the files are confusing.

### ISSUE THREAD

**Issue by otac0n** [yysun/Git-Source-Control-Provider#4]
The icon for an unmodified file is a lock, which would normally indicate that a file is locked.

The icon for a modified file is a check-mark, which would normally indicate that a file is "OK", needing no action.

Please re-evaluate the icons used for the various states of files to be less confusing.

**Comment by yysun** [comment]
The icons follow Visual Studio convention. They are the same as Source Safe and Team Foundation Server.

**Comment by otac0n** [comment]
The only reason that Team Foundation Server and Source Safe use these particular icons is that they employ a Checkout-Edit-Checkin style workflow.  SVN, Git, and etc. employ a Edit-Merge-Commit style.

That is to say that "checkout action" is not necessary to "unlock" a file in a DVCS like Git.

Therefore, the LOCK icon (while appropriate for TFS) is inappropriate for Git.

**Comment by drwelden** [comment]
The icons as described in http://msdn.microsoft.com/en-us/library/ms181372%28v=vs.80%29.aspx even indicate the workflow style otac0n described.

**Comment by yysun** [comment]
The reason of using same icons as TFS is to make Visual Studio users feel comfortable. It also makes sense to have a Git specific icons set. I am thinking to put an option let user choose which icon set to use. Is there a standard (or mostly accepted) icon set for Git?

**Comment by otac0n** [comment]
An option to change the icon set would be perfect.

Since SVN uses a similar workflow to git (with the excption of pushing and pulling, etc.)  Tortoise would be a good place to start:
![Icons](http://tortoisesvn.tigris.org/images/Overlays.png)

There are several different options.  However, there are several common themes between most icon sets:
- Normal: **green** or **check mark**, indicating that everything is "OK" with this file.
- Added: **plus**
- Modified: **red** or **orange**, as a sort of "warning" that there are uncommitted changes.
- Deleted: **red** and **crossed out**
- Ignored: **grey**, indicating that this file is unimportant to the repo
- Conflicted: **yellow** or **red** to draw attention, and **exclamation point** or **triangle** to draw a similarity to road warning signs
- Unversioned: **question mark** or **blank**

**Comment by xelibrion** [comment]
+1 for Tortoise icons

**Comment by yysun** [comment]
added the option in V0.6.4.
