### ISSUE TITLE
When comparing files, Visual Studio's interface is frozen.

### ISSUE THREAD

**Issue by otac0n** [yysun/Git-Source-Control-Provider#5]
When you right-click on a modified file, and choose Git -> Compare..., Visual Studio's interface is locked until the compare application exits.

**Comment by yysun** [comment]
It is as designed to force user close the compare app. Not good?

**Comment by otac0n** [comment]
It prevents me from being able to compare two sets of files at once.

**Comment by yysun** [comment]
changed to non-modal window in V0.6.4.
