### ISSUE TITLE
Adding new file to project using solution explorer does not add it to git repository

### ISSUE THREAD

**Issue by xelibrion** [yysun/Git-Source-Control-Provider#7]

**Comment by otac0n** [comment]
I don't see how this is a problem with the Git source control provider.

Git uses the staging area to prepare commits, and adding a file to the staging area will not prevent it from becoming stale when it is edited.

**Comment by xelibrion** [comment]
So it is not possible to implement at all? I used VisualHg some time ago and I really liked this feature.

**Comment by otac0n** [comment]
Well, the thing is that Mercurial does not have the "staging" area that Git has, and so "adding" a file to Git has a different meaning.

"Adding" a file to git takes a snapshot of the current file and puts that in the index.  Whereas adding a file in SVN or Hg adds that file to the list of files to be tracked.

That being said, "adding" a file when it is created doesn't really do what you expect, when coming from the SVN or Hg world.
