### ISSUE TITLE
Pending Changes diff view doesn't match the dark theme in Visual Studio 2012

### ISSUE THREAD

**Issue by sharwell** [yysun/Git-Source-Control-Provider#76]

**Comment by yysun** [comment]
Better to use the visual studio code editor, I think.

**Comment by sharwell** [comment]
I agree for several reasons actually:
1. Improved ability to customize fonts & colors through the standard options panel
2. Classifier used for coloring in the Pending Changes panel can also provide standard highlighting support for .diff and .patch files in the IDE
3. Look & Feel of the AvalonEdit control is not the same as the VS editor
4. No need to load AvalonEdit (faster, smaller)

I have a lot of experience in this area (it's what I do professionally) so I should be able to provide a solid implementation of everything required with very little effort.

**Comment by yysun** [comment]
2a2dcdd is the commit visual studio editor was replaced by Avalon editor.
Its parent 27f9dca has the diff classifier for visual studio editor.

**Comment by sharwell** [comment]
It looks like the classifier code is all still in the working copy (including the `ToolWindowWithEditor` control), but they are now excluded from the solution. Were there problems with the previous method? The relevant commit that changed things is ae6db478c5a22c7cb9ff9603f01bd88afdf4f67b, but I don't see any additional explanation for why that commit was needed.
